#!/bin/bash

source ${OPENSHIFT_REPO_DIR}/.openshift/.leinrc

cd ${OPENSHIFT_REPO_DIR}

echo Making UberJar
nohup ${OPENSHIFT_DATA_DIR}/lein do clean, uberjar
echo Starting The UberJar...
nohup java -jar target/uberjar/cljbuild.jar >${OPENSHIFT_LOG_DIR}/server.log 2>&1 &
