language: clojure

before_install:
  - npm install -g bower
  - cd dev-resources/libs && bower install
  - cd components/semantic && npm install && gulp build

jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/.m2"
    - "dev-resources/libs/components"
